### ISSUE TITLE
An exception error when run '2-Label-Trajectory-All.py'

### ISSUE THREAD

**Issue by ivechan** [sinadabiri/Deep-Semi-Supervised-GPS-Transport-Mode#1]
Dear Dr. Dabiri

Firstly, thank you for your great job in Semi-Supervised Deep Learning Approach for Transportation Mode Identification Using GPS Trajectory Data and your sharing codes on Github.

Unfortunately, I got into a trouble when run '2-Label-Trajectory-All.py'.
I have tried to fix it myself but I failed. 

Here are my environment and reproduce steps.
**My environment**
1. Ubuntu 18.04.2 LTS
2. Python 3.6.8 :: Anaconda, Inc.

**Reproduce steps**
1. I cloned your code. Then I downloaded GeoLife datasets and unzip it into directory "../Geolife Trajectories 1.3-Raw-All".  
2. execute `python 2-Label-Trajectory-All.py` and an error occurs:

```
Traceback (most recent call last):
  2     File "2_Label_Trajectory_All.py", line 105, in <module>
  3     ¦   raise e
  4     File "2_Label_Trajectory_All.py", line 101, in <module>
  5     ¦   trajectory_all_user_with_labetory-All.pyk)
  6 IndexError: list index out of range
```
I would really appreciate it if you could give me an tip about solving this problem.
**Thank you very very much.**

**Comment by lzhmarkk** [comment]
Seems there are some bugs about the array pointer "start_index".

My solution looks like this
```
if trajectory_user[-1][2] < end:
    end_index = start_index - 1 + len(trajectory_user) # here
    classes[mode].extend(list(range(start_index, end_index)))
    break
else:
    for index2, trajectory in enumerate(trajectory_user):
        if trajectory[2] > end:
            end_index = start_index + 1 + index2
            trajectory_user = trajectory_user[index2:] # here
            classes[mode].extend(list(range(start_index, end_index)))
            start_index = end_index # and here
            break
```

**Comment by christianll9** [comment]
@lzhmarkk your code seems also wrong to me. The values of `end_index` seems correct to me, so no need for subtracting.
Instead the value for the `start_index` in the last line needs to be lower:
```python
if trajectory_user[-1][2] < end:
    end_index = start_index + 1 + len(trajectory_user) #no change here
    classes[mode].extend(list(range(start_index, end_index)))
    break
else:
    for index2, trajectory in enumerate(trajectory_user):
        if trajectory[2] > end:
            end_index = start_index + 1 + index2
            trajectory_user = trajectory_user[index2:] # change suggested by lzhmarkk
            classes[mode].extend(list(range(start_index, end_index)))
            start_index = end_index - 1 # also here (but different than lzhmarkk)
            break
```
This code runs without error.
